name: Deploy eshop

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN}}
      - name: Run playbook
        uses: aimerib/ansible-playwright@v2
        with:
          playbook: ec2_deploy.yml
          directory: ./ansible/
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory .hosts
            --limit group1
            --extra-vars hello=there
            --verbose

